### ISSUE TITLE
Add function to calculate verifier digit into SellsUtils.pas

### ISSUE THREAD

**Issue by ricardovsilva** [ricardovsilva/fatecsp-alp#1]
This work consists in open file SellsUtils.pas and do the following changes:
- Create new function to calculate Verifier Digit:
  - function CalculateVerifierDigit(sellCode : string) : string.
  - This function will receive as parameter one string of length 4 that contains the sell code used to calculate the verifier digit.
  - This function will pass char by char of string (using for loop) and apply the digit verifier rule (see below) to calculate digit verifier.
# The algorithm
1. Receives the sell code, as string, and inherate (or pass) char by char of string.
2. Gets first char, converts to integer, and multiply by 5. Stores result of multiply.
3. Gets second char, converts to integer, and multiply by 4. Stores result of multiply.
4. Gets third char, converts to integer, and multiply by 3. Stores result of multiply.
5. Gets fourth char, converts to integer, and multiply by 2. Stores result of multiply.
6. Gets all multiply results and sum.
7. Gets sum result, divides per 7 and gets the rest of division (uses operator MOD for this).
8. Parse result into string, and return this string.

**Comment by orenantiago** [comment]
I created the function CalculateVerifierDigit on the file 'SellsUtils.pas'. The alterations are on the commit: https://github.com/ricardovsilva/fatecsp-alp/commit/6bd603fb1a801de1dee4e84757db915f57981186

**Comment by ricardovsilva** [comment]
Fully functional as from this commit https://github.com/ricardovsilva/fatecsp-alp/commit/3d1ed461e4fd139b13aed537ac87c995e532347a
