### ISSUE TITLE
Change function SellToString of SellsUtils.pas to add Verifier Digit

### ISSUE THREAD

**Issue by ricardovsilva** [ricardovsilva/fatecsp-alp#2]
This issue only can be solved after following task be solved: https://github.com/ricardovsilva/fatecsp-alp/issues/1

This function, actually, receives one record of type Sell and returns a string representation of this.
This string consists of the following values, separated by dot coma (;) :
productCode (without verifier digit) ; sellDateTime; Quantity; FinalPrice;

Example:
1234;2014-10-20;15;1230.25;

We need to add verifier digit at the code, for this uses function created into https://github.com/ricardovsilva/fatecsp-alp/issues/1 .

**Comment by orenantiago** [comment]
I closed the issue on the commit: https://github.com/ricardovsilva/fatecsp-alp/commit/fa86b7ac292400ecca7e4836f6f1ce5a3d71465a
