### ISSUE TITLE
WeekDay function are returning wrong value

### ISSUE THREAD

**Issue by ricardovsilva** [ricardovsilva/fatecsp-alp#21]
For an friday it's returning 1, We need to fix this.

**Comment by izaacsilva** [comment]
About this, you can use the function bellow
function DayOfWeek(
  DateTime: TDateTime
):Integer;
http://www.freepascal.org/docs-html/rtl/sysutils/dayofweek.html

**Comment by ricardovsilva** [comment]
Thank you :D. I was using dayOfWeek from other unit, and it's was returning long integer and crashing.
