### ISSUE TITLE
The sells module are giving wrong total of sells.

### ISSUE THREAD

**Issue by izaacsilva** [ricardovsilva/fatecsp-alp#25]
--------V E N D A S--------
Digite o ano ao qual as vendas serÒo geradas (2010 ou superior):
2014
Digite o mÛs ao qual as vendas serÒo geradas:
10
Digite a quantidade de vendas aleat¾rias a serem geradas por dia:
30
Digite a porcentagem de variaþÒo dos preþos (em inteiro): 10
30 vendas geradas com sucesso!
Pressione qualquer tecla para voltar ao menu anterior...

In the result above, the text "30 vendas geradas com sucesso!" is wrong. The correct is 30 sells \* number of working days.

**Comment by orenantiago** [comment]
Izaac, is the result to be shown on the screen only the result of the multiplication between sells number and the number of working days?
I didn't get that

**Comment by ricardovsilva** [comment]
What Izaac is saying is that is generated N sells (n is the input of quantity by user) per working day. So, my suggestion is change the text to "Sucesso ao gerar N vendas geradas por dia útil", or only "Vendas geradas com sucesso!"

**Comment by orenantiago** [comment]
The issue was closed on the commit: https://github.com/ricardovsilva/fatecsp-alp/commit/9d8cce5637d5abf2323241d90c5088909f126ff8
I just didn't change the testgenerator.exe because i had a problem on the linux pascal compiler
