### ISSUE TITLE
Add function to verify if some date is working day into DateTimeUtils.pas

### ISSUE THREAD

**Issue by ricardovsilva** [ricardovsilva/fatecsp-alp#3]
We need create one function into this file to verify if given date time is working day.
I suggest the following function:
- function IsWorkingDay(year, month, day : integer) : boolean;

This function will receive three integers variable, these variable will contains year, month and day of some Date. We will check if this date is working day (for this project, any day, except sunday, is working day).

**Comment by orenantiago** [comment]
Issue closed on commit: https://github.com/ricardovsilva/fatecsp-alp/commit/53460e24af694712d23486885c0569b421853e94
